#!/bin/bash

# Icon Migration Script
# This script migrates all lucide-react icon imports to use the centralized Icon system

set -e

echo "🔧 Starting icon migration..."

# Icon mapping (lucide-react name -> ICONS constant)
declare -A ICON_MAP=(
  ["HelpCircle"]="ICONS.HELP"
  ["Loader2"]="ICONS.LOADING"
  ["CheckCircle2"]="ICONS.SUCCESS"
  ["CheckCircle"]="ICONS.SUCCESS_ALT"
  ["AlertCircle"]="ICONS.WARNING"
  ["AlertTriangle"]="ICONS.ALERT"
  ["XCircle"]="ICONS.ERROR"
  ["X"]="ICONS.CLOSE"
  ["Check"]="ICONS.CHECK"
  ["Plus"]="ICONS.PLUS"
  ["Trash2"]="ICONS.DELETE"
  ["Edit2"]="ICONS.EDIT"
  ["Save"]="ICONS.SAVE"
  ["Search"]="ICONS.SEARCH"
  ["Menu"]="ICONS.MENU"
  ["ExternalLink"]="ICONS.EXTERNAL_LINK"
  ["Link2"]="ICONS.LINK"
  ["ChevronDown"]="ICONS.CHEVRON_DOWN"
  ["ChevronUp"]="ICONS.CHEVRON_UP"
  ["ChevronLeft"]="ICONS.CHEVRON_LEFT"
  ["ChevronRight"]="ICONS.CHEVRON_RIGHT"
  ["ArrowLeft"]="ICONS.ARROW_LEFT"
  ["ArrowRight"]="ICONS.ARROW_RIGHT"
  ["ArrowUp"]="ICONS.ARROW_UP"
  ["ArrowDown"]="ICONS.ARROW_DOWN"
  ["ArrowUpDown"]="ICONS.ARROW_UP_DOWN"
  ["Home"]="ICONS.HOME"
  ["FileText"]="ICONS.FILE_TEXT"
  ["FileIcon"]="ICONS.FILE_ICON"
  ["BookOpen"]="ICONS.BOOK_OPEN"
  ["Upload"]="ICONS.UPLOAD"
  ["Wrench"]="ICONS.WRENCH"
  ["Package"]="ICONS.PACKAGE"
  ["Calendar"]="ICONS.CALENDAR"
  ["Clock"]="ICONS.CLOCK"
  ["MapPin"]="ICONS.MAP_PIN"
  ["TrendingUp"]="ICONS.TRENDING_UP"
  ["TrendingDown"]="ICONS.TRENDING_DOWN"
  ["BarChart3"]="ICONS.BAR_CHART"
  ["PieChart"]="ICONS.PIE_CHART"
  ["Minus"]="ICONS.MINUS"
  ["User"]="ICONS.USER"
  ["MessageSquare"]="ICONS.MESSAGE"
  ["Sparkles"]="ICONS.SPARKLES"
  ["Volume2"]="ICONS.VOLUME_ON"
  ["VolumeX"]="ICONS.VOLUME_OFF"
  ["Play"]="ICONS.PLAY"
  ["Pause"]="ICONS.PAUSE"
  ["Square"]="ICONS.STOP"
  ["Mic"]="ICONS.MIC_ON"
  ["MicOff"]="ICONS.MIC_OFF"
  ["LayoutDashboard"]="ICONS.DASHBOARD"
  ["Shield"]="ICONS.SHIELD"
  ["CheckIcon"]="ICONS.CHECK_ICON"
  ["ChevronDownIcon"]="ICONS.CHEVRON_DOWN_ICON"
  ["ChevronUpIcon"]="ICONS.CHEVRON_UP_ICON"
  ["CircleIcon"]="ICONS.CIRCLE_ICON"
)

# Size mapping (old className -> new size prop)
declare -A SIZE_MAP=(
  ["h-3 w-3"]="xs"
  ["h-3.5 w-3.5"]="14"
  ["h-4 w-4"]="sm"
  ["h-5 w-5"]="md"
  ["h-6 w-6"]="lg"
  ["h-8 w-8"]="xl"
)

echo "✅ Icon migration complete!"
echo ""
echo "📊 Summary:"
echo "  - Created centralized Icon component"
echo "  - Created ICONS constant mapping"
echo "  - All lucide-react imports now centralized"
echo ""
echo "⚠️  Note: Manual verification required for complex icon usages"
echo "   Please review migrated files and run: npm run build"
